name: 哔哩哔哩签到

on:
  schedule:
    - cron: 0 22,14 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 签到
      run: |
        pip install -r bilibili/requirements.txt
        string="${{ secrets.BILIBILICOOKIE }}"
        IFS="#"
        array=($string)
        for var in ${array[@]}
        do
          python3 bilibili/checkin.py <<EOF
          $var
        EOF
        done
        
